[build]
command = "npm run build"
publish = "dist"

# Главное правило для SPA: все пути → index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true  # Важно: игнорировать существующие файлы

# Исключение для API (если есть)
[[redirects]]
from = "/api/*"
to = "https://ya-praktikum.tech/api/v2/:splat"
status = 200

# Исключение для статики (CSS/JS/изображения)
[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200
